sandbox_mode = "danger-full-access"
approval_policy = "never"

model = "gpt-5.5"
model_reasoning_effort = "medium"

[projects."/home/eimas/Projects/starch2"]
trust_level = "trusted"

[projects."/home/eimas/dotfiles"]
trust_level = "trusted"

[projects."/home/eimas/Projects/TypeScriptAddonTemplate-Fork"]
trust_level = "trusted"

[projects."/mnt/shared_data/home-system"]
trust_level = "trusted"
