monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-SteelSeries_Arctis_Nova_Pro_Wireless.*"
      }
    ]
    actions = {
      update-props = {
        node.description = "Headphones"
        node.nick = "Headphones"
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.usb-SteelSeries_Arctis_GameBuds.*"
      }
    ]
    actions = {
      update-props = {
        node.description = "Earbuds"
        node.nick = "Earbuds"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_0b_00.4.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Speakers"
        node.nick = "Speakers"
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_input.usb-SteelSeries_Arctis_Nova_Pro_Wireless.*"
      }
    ]
    actions = {
      update-props = {
        node.description = "Headphones Mic"
        node.nick = "Headphones Mic"
      }
    }
  }
]
