general {
    # 1. DEFINE THE HANDLER: When "lock-session" is signaled, run this command
    lock_cmd = pidof hyprlock || hyprlock

    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# DIM TRIGGER: After 4.5 mins, gradually dim screen
listener {
    timeout = 270
    on-timeout = ~/.config/hypr/scripts/dim.sh
    on-resume = brightnessctl -r
}

# DPMS TRIGGER: After 5 mins, turn screen off
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# LOCK TRIGGER: After 1 hour, lock session
listener {
    timeout = 3600
    on-timeout = loginctl lock-session
}
